from sklearn.feature_extraction.text import CountVectorizer

fileData = open("Articles\\Article1.txt","r")
stopwords = []
stopwords.append("to")
stopwords.append("and")
stopwords.append("how")
stopwords.append("does")
stopwords.append("us")
stopwords.append("from")
stopwords.append("the")
stopwords.append("of")
stopwords.append("can")
stopwords.append("you")
stopwords.append("looks")
stopwords.append("like")
stopwords.append("do")
stopwords.append("with")
stopwords.append("search")
stopwords.append("join")
stopwords.append("by")
stopwords.append("group")
stopwords.append("an")
stopwords.append("then")
stopwords.append("see")
stopwords.append("which")
stopwords.append("your")
stopwords.append("for")
stopwords.append("while")
stopwords.append("at")
stopwords.append("try")
stopwords.append("what")
stopwords.append("my")
stopwords.append("am")
stopwords.append("here")
stopwords.append("it")
stopwords.append("many")
stopwords.append("is")
stopwords.append("over")
stopwords.append("type")
stopwords.append("as")
stopwords.append("so")
stopwords.append("may")
stopwords.append("key")
stopwords.append("or")
stopwords.append("if")
stopwords.append("not")
stopwords.append("take")
stopwords.append("has")
stopwords.append("above")
stopwords.append("but")
sentence = fileData
#Creating an object of Count Vectorizer. Also stop words as well
cv = CountVectorizer(stop_words=stopwords)
#fit, training alogritham - Data - FIT - Train - Model - Transform - Database
#cv.fit(sentence)
#cvt = cv.transform(sentence)
cvt = cv.fit_transform(sentence)
print(cv.vocabulary_)
print(cvt)